[package]
name = "sio_rs2"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["macros", "ws"] }
futures = "0.3.31"
pin-project-lite = "0.2.16"
serde = { version = "1.0.219", features = ["derive"] }
tower = "0.5.2"
